dist:
  name: otelcol-dev
  description: Basic OTel Collector distribution for Developers
  output_path: ./otelcol-dev

exporters:
  - gomod:
#      go.opentelemetry.io/collector/exporter/datadogexporter v0.126.0
      github.com/open-telemetry/opentelemetry-collector-contrib/exporter/datadogexporter v0.126.0
  - gomod:
      # NOTE: Prior to v0.86.0 use the `loggingexporter` instead of `debugexporter`.
      go.opentelemetry.io/collector/exporter/debugexporter v0.127.0
  - gomod:
      go.opentelemetry.io/collector/exporter/otlpexporter v0.127.0

processors:
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/processor/attributesprocessor v0.127.0
  - gomod:
      go.opentelemetry.io/collector/processor/batchprocessor v0.127.0

receivers:
  - gomod:
      go.opentelemetry.io/collector/receiver/otlpreceiver v0.127.0

providers:
  - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpsprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/yamlprovider v1.18.0
